[loading]
module_dir = "/modules"
compiler_backend = "cranelift"
test_mode = false

[loading.log_type_overrides]
"hello_world.wasm" = "hello_world"

[loading.computation_amount]
default = 55_000_000

[loading.memory_page_count]
default = 300

[loading.storage_size]
default = "Unlimited"
