[workspace]
#resolver = "2"

members = [
    "plaid",
    "plaid-stl",
    "test_modules/persistent_response", "test_modules/sshcerts_usage",
    "test_modules/time",
]

[profile.release]
lto = true
strip = "symbols"
