name: Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches:  "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-integration-test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Rust
      run: |
        rustup toolchain install nightly-2024-12-14  # pinning the nightly version should help with caching dependencies
        rustup default nightly-2024-12-14
        rustup target add wasm32-unknown-unknown

    - uses: actions/checkout@v4

    - name: Runtime cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          runtime/target/
        key: ${{ runner.os }}-cargo-runtime-${{ hashFiles('runtime/Cargo.lock') }}

    # - name: Modules cache
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       modules/target/
    #     key: ${{ runner.os }}-cargo-modules-${{ hashFiles('modules/Cargo.lock') }}

    - name: Run Integration Tests
      run: ./testing/integration.sh


  # ubuntu-docker-build-amd64-test:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4

  #   - uses: actions/cache@v4
  #     with:
  #       path: |
  #         ~/.cargo/bin/
  #         ~/.cargo/registry/index/
  #         ~/.cargo/registry/cache/
  #         ~/.cargo/git/db/
  #         runtime/target/
  #       key: ${{ runner.os }}-cargo-amd64-${{ hashFiles('**/Cargo.lock') }}
    
  #   - name: Run Docker Build Test (amd64)
  #     run: cd runtime && docker build -t latest -f plaid/resources/Dockerfile.amd64 .


  # ubuntu-docker-build-aarch64-test:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4

  #   - uses: actions/cache@v4
  #     with:
  #       path: |
  #         ~/.cargo/bin/
  #         ~/.cargo/registry/index/
  #         ~/.cargo/registry/cache/
  #         ~/.cargo/git/db/
  #         runtime/target/
  #       key: ${{ runner.os }}-cargo-aarch64-${{ hashFiles('**/Cargo.lock') }}
    
  #   - name: Run Docker Build Test (aarch64)
  #     run: cd runtime && docker build -t latest -f plaid/resources/Dockerfile.aarch64 .

  