name: Module Checker

on:
  workflow_call:

permissions:
  contents: write

jobs:
  release_module_checker:
    name: Release module checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build module checker
        run: |
          cd runtime
          rustup toolchain install 1.86.0
          rustup default 1.86.0
          cargo build --bin module_checker --no-default-features --features cranelift

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: module_checker
          path: runtime/target/debug/module_checker
